aws_access_key_id: "<your-aws-access-key-id>"
aws_secret_access_key: "<your-aws-secret-access-key>"
s3_bucket_name: "<your-s3-bucket-name>"
mongodb_url: "mongodb://localhost:27017/"
rmq_user: "<rabbitmq-username>"
rmq_pass: "<rabbitmq-password>"
rmq_host: "localhost"
rmq_vhost: "entries"
rmq_topic: "<TOPIC_NAME>"
image_dir: "<IMAGE_SAVE_PATH>"
model_path: "yolov7.pt"